# Generated by Django 4.2.9 on 2024-01-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorEvento', '0002_usuariopersonalizado_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.CharField(max_length=200),
        ),
    ]
