# Generated by Django 4.2.9 on 2024-01-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorEvento', '0003_alter_evento_categoria_alter_evento_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='participantes',
        ),
        migrations.DeleteModel(
            name='Participante',
        ),
    ]
